### ISSUE TITLE
programmer_art assets don't appear to be injecting

### ISSUE THREAD

**Issue by shmoobalizer** [ExtraCrafTX/ProgrammerArtInjector#3]
I really appreciate that you made this mod, but I can't seem to make it work. 

I followed the usage instructions as written in the readme, and the resources in the programmer_art folder simply don't appear in the game, regardless of if the programmer art pack is applied or not. 

Sorry if this report isn't helpful, but I don't know what other information to add, it simply isn't working. 

EDIT: Sorry, it seems it's started working now.

**Comment by shmoobalizer** [comment]
EDIT: Sorry, it seems it's started working now.

**Comment by ExtraCrafTX** [comment]
No worries, good to hear it started working.
